In [3]:
import numpy as np
import pandas as pd
from pathlib import Path
import os
import statsmodels.api as sm
import pickle

In [2]:
lis = pd.DataFrame(os.listdir("/home/harshit/Project/complete_models/"))
coeff = pd.DataFrame(columns = ["Symbol","const","SMB %", "HML %","Rm-Rf %", "high-low"] )
#Making a dataframe of all coffecients
for i in lis[0]:
    data = open("/home/harshit/Project/complete_models/"+i,"rb")
    symbol = i.split('.')[0]
    model = pickle.load(data)
    frame = pd.DataFrame(model.params).T
    frame.insert(0,"Symbol",symbol)
    coeff = coeff.append(frame,ignore_index=True,sort=False)
intercept =coeff['const']

In [3]:
all_factors= pd.read_csv("/home/harshit/Project/allfactors.csv")

In [2]:
#Calculating residuals
model_path = "/home/harshit/Project/complete_models/"
return_path = "/home/harshit/Project/Returns/all_ret_by_company/"
mod = os.listdir(model_path)
ret = os.listdir(return_path)
residuals = pd.DataFrame()
for i in ret:
    i = i.split(".")[0]
    equity = pd.read_csv(return_path+i+".csv")                       # loading daily Return data
    equity.Date = equity.Date.apply(lambda x: x.replace("-",""))
    equity["Date"] = equity["Date"].apply(pd.to_numeric)
    equity=equity.drop([0])
    
    all_data = pd.merge(all_factors,equity,on="Date")
    all_data.rename(columns={'Return':i}, inplace=True)
    X= all_data[["SMB %","HML %","WML %","Rm-Rf %","high-low"]] #Making X variable for entropy included model
    X= sm.add_constant(X)
    y = all_data[i]
    
    
    data = open("/home/harshit/Project/complete_models/"+i+".sav","rb") # loading model
    symbol = i.split('.')[0]
    model = pickle.load(data)
    residual = y - pd.DataFrame(model.predict(X),columns=[i])
    residual= pd.merge(all_data[["Date"]],residual,left_index=True, right_index=True)
    residual = residual.T
    residuals = residuals.append(residual)
residuals.reset_index(inplace=True)

NameError: name 'os' is not defined

In [1]:
residuals

NameError: name 'residuals' is not defined

In [135]:
equity

           Date               Return
1    2013-01-02                 0.64
2    2013-01-03                -0.85
3    2013-01-04                -0.15
4    2013-01-07                -1.16
5    2013-01-08                -1.31
6    2013-01-09                 1.56
7    2013-01-10                 1.09
8    2013-01-11                 2.64
9    2013-01-14                -1.48
10   2013-01-15                -1.52
11   2013-01-16                 1.56
12   2013-01-17                -0.92
13   2013-01-18                 1.58
14   2013-01-21                 0.03
15   2013-01-22                 0.84
16   2013-01-23                 0.16
17   2013-01-24                 0.05
18   2013-01-25                -2.09
19   2013-01-28                -1.77
20   2013-01-29                 0.66
21   2013-01-30                 1.39
22   2013-01-31                 0.41
23   2013-02-01                -0.56
24   2013-02-04                 1.52
25   2013-02-05                 0.30
26   2013-02-06                -1.59
27   2013-02-07                 7.46
28   2013-02-08                -4.12
29   2013-02-11                 1.37
30   2013-02-12                 0.16
...         ...                  ...
1207 2017-11-17                 0.61
1208 2017-11-20                -0.87
1209 2017-11-21                 0.57
1210 2017-11-22                -0.90
1211 2017-11-23                 0.95
1212 2017-11-24                -0.58
1213 2017-11-27                -0.39
1214 2017-11-28               -10.32
1215 2017-11-29                -3.92
1216 2017-11-30                 3.54
1217 2017-12-01                 0.08
1218 2017-12-04                -3.21
1219 2017-12-05                 0.86
1220 2017-12-06                -0.79
1221 2017-12-07                 0.68
1222 2017-12-08               -13.45
1223 2017-12-11               -16.55
1224 2017-12-12                 0.80
1225 2017-12-13                -4.51
1226 2017-12-14                -0.47
1227 2017-12-15                -0.91
1228 2017-12-18                 2.21
1229 2017-12-19                -1.25
1230 2017-12-20                 0.74
1231 2017-12-21                -4.09
1232 2017-12-22                -0.43
1233 2017-12-26                 2.35
1234 2017-12-27                 1.76
1235 2017-12-28                -2.28
1236 2017-12-29                 1.70

[1236 rows x 2 columns]